name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies and generate lockfile
        run: npm install
        working-directory: server_app

      - name: Install dependencies using package-lock.json
        run: npm ci
        working-directory: server_app

      - name: Build
        run: npm run build --if-present
        working-directory: server_app

      - name: Test
        run: npm test
        working-directory: server_app

      - name: Integration Test
        run: npm run itest
        working-directory: server_app
